/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : IFsh1.C
**     Project   : Connector_App
**     Processor : MC9S12E64CFU
**     Beantype  : IntFLASH
**     Version   : Bean 02.118, Driver 02.01, CPU db: 2.87.373
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 6/8/2005, 6:19 PM
**     Abstract  :
**         This bean "IntFLASH" implements an access to internal FLASH.
**         The bean support reading/writing data into FLASH, erasing of 
**         selected sector.
**         The bean supports events if the write interrupt is supported.
**         The bean supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The bean requires on-chip FLASH memory (not used/allocated by 
**         other beans).
**     Settings  :
**         Total FLASH memory size       : 64KB
**         Interrupt service             : Disabled
**         Write method                  : Write
**         Wait in RAM                   : no
**     Contents  :
**         SetProtection - byte IFsh1_SetProtection(bool ProtectType,byte ProtectHigh,byte ProtectLow,by...
**         SetByteFlash  - byte IFsh1_SetByteFlash(dword Addr,byte Data);
**         SetWordFlash  - byte IFsh1_SetWordFlash(dword Addr,word Data);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE IFsh1. */

#include "IFsh1.h"


/* Definition of DATA and CODE segments for this bean. User can specify where
   these segments will be located on "Build options" tab of the selected CPU bean. */
#pragma DATA_SEG IFsh1_DATA            /* Data section for this module. */
#pragma CODE_SEG IFsh1_CODE            /* Code section for this module. */

/* Global variables */





/*
** ===================================================================
**     Method      :  ClearFlags (bean IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static void ClearFlags(void)
{
  byte i;

  for (i = 0; i <= 0; i++) {
    FSTAT = 48;                        /* Clear PVIOL & ACERR flag */
  }
}

/*
** ===================================================================
**     Method      :  WriteWord (bean IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static byte WriteWord(dword Addr,word Data16)
{
  EnterCritical();                     /* Enter critical section */
  ClearFlags();                        /* Clear all flags */
  if (FSTAT_CBEIF == 0) {              /* Is command buffer full ? */
    ExitCritical();                    /* Exit critical section */
    return ERR_BUSY;                   /* If yes then error */
  }
  *(word *far) Addr = Data16;          /* Array address and program data */
  FCMD = 32;                           /* Word program command */
  FSTAT = 128;                         /* Clear flag command buffer empty */
  if ((FSTAT_PVIOL == 1)||(FSTAT_ACCERR == 1)) { /* Is protection violation or acces error detected ? */
    ExitCritical();                    /* Exit critical section */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  while (FSTAT_CBEIF == 0);            /* Wait to buffer empty */
  while (FSTAT_CCIF == 0);             /* Wait to command complete */
  ExitCritical();                      /* Exit critical section */
  if (*(word *far) Addr != Data16)     /* Was attempt to write data to the given address errorneous? */
    return ERR_VALUE;                  /* If yes then error */
 return ERR_OK;                        /* OK */
}
/*
** ===================================================================
**     Method      :  IFsh1_SetProtection (bean IntFLASH)
**
**     Description :
**         Method allows write to protection register. Please see
**         Flash Block User Guide.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ProtectType     - Possible values: 0 or 1.
**                           Depend on CPU type. Two sense are
**                           possible.
**                           First:
**                           - 0 = whole Flash array is protected. In
**                           this case other parameters are don't
**                           care.
**                           - 1 = protection size depend on
**                           ProtectHigh and ProtectLow parameters.
**                           Second:
**                           - 0 = ProtectHigh and ProtectLow
**                           parameters define range to by protected .
**                           - 1 = ProtectHigh and ProtectLow
**                           parameters define range to by
**                           unprotected .
**         ProtectHigh     - Flash higher address
**                           range protection. Possible values:
**                           - 0 - 3 - defines range (size of range
**                           depend on CPU type) , 4 - Protection
**                           disabled
**         ProtectLow      - Flash lower address
**                           range protection. Possible values:
**                           - 0 - 3 - defines range (size of range
**                           depend on CPU type) , 4 - Protection
**                           disabled
**         Block           - Flash block number. Number of
**                           blocks depend on CPU type. If CPU has
**                           only one block, the value is don't care.
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_RANGE - Value is out of range
**                           - ERR_VALUE - Parameter of incorrect
**                           value
**                           - ERR_SPEED - This device does not work
**                           in the active speed mode
** ===================================================================
*/
byte IFsh1_SetProtection(bool ProtectType,byte ProtectHigh,byte ProtectLow,byte Block)
{
  byte TempFPROT;

  if ((Block > 0)||(ProtectHigh > 4)||(ProtectLow > 4)||(ProtectType > 1)) /* Range check */
    return ERR_RANGE;
  TempFPROT = (ProtectType<<7) | (ProtectHigh<<3) | ProtectLow; /* Set temoraly variable */
  FPROT = TempFPROT;                   /* Set new protection */
  if (FPROT != TempFPROT)
    return ERR_VALUE;                  /* Was protection register set corectly? */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IFsh1_SetByteFlash (bean IntFLASH)
**
**     Description :
**         Write byte to address in FLASH.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to FLASH.
**         Data            - Data to write.
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available
**                           - ERR_RANGE - Address is out of range
**                           - ERR_VALUE - Read value is not equal to
**                           written value
**                           - ERR_SPEED - This device does not work
**                           in the active speed mode
**                           - ERR_BUSY - Device is busy
** ===================================================================
*/
byte IFsh1_SetByteFlash(dword Addr,byte Data)
{
  byte err;

  if(((Addr&65535)<32768)||((Addr&65535)>49151)||((Addr>>16)<60)||((Addr>>16)>63))
    return(ERR_RANGE);                 /* Check range of address */
  if (Addr&1) {                        /* Not Aligned word ? */
    err=WriteWord(Addr & 16777214, ((*(word *far)(Addr & 16777214)) & 65280) | Data);
  } else {
    err=WriteWord(Addr & 16777214, (Data<<8) | ((*(word *far)Addr) & 255));
  }
  return(err);                         /* Return error code if previous operation finished not correctly */
}

/*
** ===================================================================
**     Method      :  IFsh1_SetWordFlash (bean IntFLASH)
**
**     Description :
**         Write word to address in FLASH.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to FLASH.
**         Data            - Data to write.
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available
**                           - ERR_RANGE - Address is out of range
**                           - ERR_VALUE - Read value is not equal to
**                           written value
**                           - ERR_SPEED - This device does not work
**                           in the active speed mode
**                           - ERR_BUSY - Device is busy
** ===================================================================
*/
byte IFsh1_SetWordFlash(dword Addr,word Data)
{
  byte err;

  if(((Addr&65535)<32768)||((Addr&65535)>49150)||((Addr>>16)<60)||((Addr>>16)>63))
    return(ERR_RANGE);                 /* Check range of address */
  if (Addr & 1)                        /* Aligned address ? */
    return ERR_NOTAVAIL;
  err = WriteWord(Addr, Data);         /* Write new data to Flash */
  return(err);                         /* Return error */
}


/*
** ===================================================================
**     Method      :  IFsh1_Init (bean IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void IFsh1_Init(void)
{
  FCLKDIV = 74;                        /* Set up Clock Divider Register */
}


/* END IFsh1. */


/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.33 for 
**     the Motorola HCS12 series of microcontrollers.
**
** ###################################################################
*/
