/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : IO_Map.C
**     Project   : Connector_App
**     Processor : MC9S12E64CFU
**     Beantype  : IO_Map
**     Version   : Driver 01.01
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 6/8/2005, 6:19 PM
**     Abstract  :
**         This bean "IO_Map" implements an IO devices mapping.
**     Settings  :
**
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/
/* Based on CPU DB MC9S12E128_80, version 2.87.369 */
#include "PE_types.h"
#include "IO_Map.h"

volatile ARMCOPSTR _ARMCOP;                                /* CRG COP Timer Arm/Reset Register */
volatile ATDSTAT0STR _ATDSTAT0;                            /* ATD Status Register 0 */
volatile ATDSTAT1STR _ATDSTAT1;                            /* ATD Status Register 1 */
volatile ATDSTAT2STR _ATDSTAT2;                            /* ATD Status Register 2 */
volatile CLKSELSTR _CLKSEL;                                /* CRG Clock Select Register */
volatile COPCTLSTR _COPCTL;                                /* CRG COP Control Register */
volatile CRGFLGSTR _CRGFLG;                                /* CRG Flags Register */
volatile CRGINTSTR _CRGINT;                                /* CRG Interrupt Enable Register */
volatile CTCTLSTR _CTCTL;                                  /* CRG Test Control Register */
volatile CTFLGSTR _CTFLG;                                  /* CRG Test Flags Register */
volatile DAC0_DACC0STR _DAC0_DACC0;                        /* DAC0 Control Register 0 */
volatile DAC0_DACDLeftSTR _DAC0_DACDLeft;                  /* DAC0 Data Register - Left Justified */
volatile DAC0_DACDRightSTR _DAC0_DACDRight;                /* DAC0 Data Register - Right Justified */
volatile DAC1_DACC0STR _DAC1_DACC0;                        /* DAC1Control Register 0 */
volatile DAC1_DACDLeftSTR _DAC1_DACDLeft;                  /* DAC1 Data Register - Left Justified */
volatile DAC1_DACDRightSTR _DAC1_DACDRight;                /* DAC1 Data Register - Right Justified */
volatile DBGC1STR _DBGC1;                                  /* Debug Control Register 1 */
volatile DBGC2STR _DBGC2;                                  /* Debug Control Register 2 */
volatile DBGC3STR _DBGC3;                                  /* Debug Control Register 3 */
volatile DBGCAHiSTR _DBGCAHi;                              /* Debug Comparator A Register High */
volatile DBGCALoSTR _DBGCALo;                              /* Debug Comparator A Register Low */
volatile DBGCAXSTR _DBGCAX;                                /* Debug Comparator A Extended Register */
volatile DBGCBHiSTR _DBGCBHi;                              /* Debug Comparator B Register High */
volatile DBGCBLoSTR _DBGCBLo;                              /* Debug Comparator B Register Low */
volatile DBGCBXSTR _DBGCBX;                                /* Debug Comparator B Extended Register */
volatile DBGCCHiSTR _DBGCCHi;                              /* Debug Comparator C Register High */
volatile DBGCCLoSTR _DBGCCLo;                              /* Debug Comparator C Register Low */
volatile DBGCCXSTR _DBGCCX;                                /* Debug Comparator C Extended Register */
volatile DBGCNTSTR _DBGCNT;                                /* Debug Count Register */
volatile DBGSCSTR _DBGSC;                                  /* Debug Status and Control Register */
volatile DBGTBHiSTR _DBGTBHi;                              /* Debug Trace Buffer Register High */
volatile DBGTBLoSTR _DBGTBLo;                              /* Debug Trace Buffer Register Low */
volatile DDRESTR _DDRE;                                    /* Port E Data Direction Register */
volatile DDRKSTR _DDRK;                                    /* Port K Data Direction Register */
volatile DDRMSTR _DDRM;                                    /* Port M Data Direction Register */
volatile DDRPSTR _DDRP;                                    /* Port P Data Direction Register */
volatile DDRQSTR _DDRQ;                                    /* Port Q Data Direction Register */
volatile DDRSSTR _DDRS;                                    /* Port S Data Direction Register */
volatile DDRTSTR _DDRT;                                    /* Port T Data Direction Register */
volatile DDRUSTR _DDRU;                                    /* Port U Data Direction Register */
volatile EBICTLSTR _EBICTL;                                /* External Bus Interface Control */
volatile FCLKDIVSTR _FCLKDIV;                              /* Flash Clock Divider Register */
volatile FCMDSTR _FCMD;                                    /* Flash Command Buffer and Register */
volatile FCNFGSTR _FCNFG;                                  /* Flash Configuration Register */
volatile FORBYPSTR _FORBYP;                                /* Crg force and bypass test register */
volatile FPROTSTR _FPROT;                                  /* Flash Protection Register */
volatile FSECSTR _FSEC;                                    /* Flash Security Register */
volatile FSTATSTR _FSTAT;                                  /* Flash Status Register */
volatile HPRIOSTR _HPRIO;                                  /* Highest Priority I Interrupt */
volatile IBADSTR _IBAD;                                    /* IIC Address Register */
volatile IBCRSTR _IBCR;                                    /* IIC Control Register */
volatile IBDRSTR _IBDR;                                    /* IIC Data I/O Register */
volatile IBFDSTR _IBFD;                                    /* IIC Frequency Divider Register */
volatile IBSRSTR _IBSR;                                    /* IIC Status Register */
volatile INITEESTR _INITEE;                                /* Initialization of Internal EEPROM Position Register */
volatile INITRGSTR _INITRG;                                /* Initialization of Internal Register Position Register */
volatile INITRMSTR _INITRM;                                /* Initialization of Internal RAM Position Register */
volatile INTCRSTR _INTCR;                                  /* Interrupt Control Register */
volatile ITCRSTR _ITCR;                                    /* Interrupt Test Control Register */
volatile ITESTSTR _ITEST;                                  /* Interrupt Test Register */
volatile MEMSIZ0STR _MEMSIZ0;                              /* Memory Size Register Zero */
volatile MEMSIZ1STR _MEMSIZ1;                              /* Memory Size Register One */
volatile MISCSTR _MISC;                                    /* Miscellaneous Mapping Control Register */
volatile MODESTR _MODE;                                    /* Mode Register */
volatile MODRRSTR _MODRR;                                  /* Port U Module Routing Register */
volatile MTST0STR _MTST0;                                  /* MTST0 */
volatile MTST1STR _MTST1;                                  /* MTST1 */
volatile PARTIDHSTR _PARTIDH;                              /* Part ID Register High */
volatile PARTIDLSTR _PARTIDL;                              /* Part ID Register Low */
volatile PEARSTR _PEAR;                                    /* Port E Assignment Register */
volatile PERMSTR _PERM;                                    /* Port M Pull Device Enable Register */
volatile PERPSTR _PERP;                                    /* Port P Pull Device Enable Register */
volatile PERQSTR _PERQ;                                    /* Port Q Pull Device Enable Register */
volatile PERSSTR _PERS;                                    /* Port S Pull Device Enable Register */
volatile PERTSTR _PERT;                                    /* Port T Pull Device Enable Register */
volatile PERUSTR _PERU;                                    /* Port U Pull Device Enable Register */
volatile PLLCTLSTR _PLLCTL;                                /* CRG PLL Control Register */
volatile PMFCCTLSTR _PMFCCTL;                              /* PMF correction control register */
volatile PMFCFG0STR _PMFCFG0;                              /* PMF Configure 0 Register */
volatile PMFCFG1STR _PMFCFG1;                              /* PMF Configure 1 Register */
volatile PMFCFG2STR _PMFCFG2;                              /* PMF Configure 2 Register */
volatile PMFCFG3STR _PMFCFG3;                              /* PMF Configure 3 Register */
volatile PMFDMPASTR _PMFDMPA;                              /* PMF disable mapping A register */
volatile PMFDMPBSTR _PMFDMPB;                              /* PMF disable mapping B register */
volatile PMFDMPCSTR _PMFDMPC;                              /* PMF disable mapping C register */
volatile PMFDTMSSTR _PMFDTMS;                              /* PMF deadtime sample register */
volatile PMFENCASTR _PMFENCA;                              /* PMF Enable Control A Register */
volatile PMFENCBSTR _PMFENCB;                              /* PMF enable control B register */
volatile PMFENCCSTR _PMFENCC;                              /* PMF Enable Control C Register */
volatile PMFFCTLSTR _PMFFCTL;                              /* PMF fault control register */
volatile PMFFPINSTR _PMFFPIN;                              /* PMF fault acknowledge register */
volatile PMFFQCASTR _PMFFQCA;                              /* PMF Frequency Control A Register */
volatile PMFFQCBSTR _PMFFQCB;                              /* PMF Frequency Control B Register */
volatile PMFFQCCSTR _PMFFQCC;                              /* PMF Frequency Control C Register */
volatile PMFFSTASTR _PMFFSTA;                              /* PMF fault status register */
volatile PMFOUTBSTR _PMFOUTB;                              /* PMF output control bit register */
volatile PMFOUTCSTR _PMFOUTC;                              /* PMF output control register */
volatile PMFQSMPSTR _PMFQSMP;                              /* PMF fault qualifying samples register */
volatile PORTAD0STR _PORTAD0;                              /* Port AD0 Register */
volatile PORTAD1STR _PORTAD1;                              /* Port AD1 Register */
volatile PORTESTR _PORTE;                                  /* Port E Register */
volatile PORTKSTR _PORTK;                                  /* Port K Data Register */
volatile PPAGESTR _PPAGE;                                  /* Page Index Register */
volatile PPSMSTR _PPSM;                                    /* Port M Polarity Select Register */
volatile PPSPSTR _PPSP;                                    /* Port P Polarity Select Register */
volatile PPSQSTR _PPSQ;                                    /* Port Q Polarity Select Register */
volatile PPSSSTR _PPSS;                                    /* Port S Polarity Select Register */
volatile PPSTSTR _PPST;                                    /* Port T Polarity Select Register */
volatile PPSUSTR _PPSU;                                    /* PortJP Polarity Select Register */
volatile PTIMSTR _PTIM;                                    /* Port M Input */
volatile PTIPSTR _PTIP;                                    /* Port P Input */
volatile PTIQSTR _PTIQ;                                    /* Port Q Input Register */
volatile PTISSTR _PTIS;                                    /* Port S Input */
volatile PTITSTR _PTIT;                                    /* Port T Input */
volatile PTIUSTR _PTIU;                                    /* Port U Input Register */
volatile PTMSTR _PTM;                                      /* Port M I/O Register */
volatile PTPSTR _PTP;                                      /* Port P I/O Register */
volatile PTQSTR _PTQ;                                      /* Port Q I/O Register */
volatile PTSSTR _PTS;                                      /* Port S I/O Register */
volatile PTTSTR _PTT;                                      /* Port T I/O Register */
volatile PTUSTR _PTU;                                      /* Port U I/O Register */
volatile PUCRSTR _PUCR;                                    /* Pull-Up Control Register */
volatile PWMCAESTR _PWMCAE;                                /* PWM Center Align Enable Register */
volatile PWMCLKSTR _PWMCLK;                                /* PWM Clock Select Register */
volatile PWMCTLSTR _PWMCTL;                                /* PWM Control Register */
volatile PWMESTR _PWME;                                    /* PWM Enable Register */
volatile PWMPOLSTR _PWMPOL;                                /* PWM Polarity Register */
volatile PWMPRCLKSTR _PWMPRCLK;                            /* PWM Prescale Clock Select Register */
volatile PWMSCLASTR _PWMSCLA;                              /* PWM Scale A Register */
volatile PWMSCLBSTR _PWMSCLB;                              /* PWM Scale B Register */
volatile PWMSDNSTR _PWMSDN;                                /* PWM Shutdown Register */
volatile RDRIVSTR _RDRIV;                                  /* Reduced Drive of I/O Lines */
volatile RDRMSTR _RDRM;                                    /* Port M Reduced Drive Register */
volatile RDRPSTR _RDRP;                                    /* Port P Reduced Drive Register */
volatile RDRQSTR _RDRQ;                                    /* Port Q Reduced Drive Register */
volatile RDRSSTR _RDRS;                                    /* Port S Reduced Drive Register */
volatile RDRTSTR _RDRT;                                    /* Port T Reduced Drive Register */
volatile RDRUSTR _RDRU;                                    /* Port U Reduced Drive Register */
volatile REFDVSTR _REFDV;                                  /* CRG Reference Divider Register */
volatile RTICTLSTR _RTICTL;                                /* CRG RTI Control Register */
volatile SCI0CR1STR _SCI0CR1;                              /* SCI 0 Control Register 1 */
volatile SCI0CR2STR _SCI0CR2;                              /* SCI 0 Control Register 2 */
volatile SCI0DRHSTR _SCI0DRH;                              /* SCI 0 Data Register High */
volatile SCI0DRLSTR _SCI0DRL;                              /* SCI 0 Data Register Low */
volatile SCI0SR1STR _SCI0SR1;                              /* SCI 0 Status Register 1 */
volatile SCI0SR2STR _SCI0SR2;                              /* SCI 0 Status Register 2 */
volatile SCI1CR1STR _SCI1CR1;                              /* SCI 1 Control Register 1 */
volatile SCI1CR2STR _SCI1CR2;                              /* SCI 1 Control Register 2 */
volatile SCI1DRHSTR _SCI1DRH;                              /* SCI 1 Data Register High */
volatile SCI1DRLSTR _SCI1DRL;                              /* SCI 1 Data Register Low */
volatile SCI1SR1STR _SCI1SR1;                              /* SCI 1 Status Register 1 */
volatile SCI1SR2STR _SCI1SR2;                              /* SCI 1 Status Register 2 */
volatile SCI2CR1STR _SCI2CR1;                              /* SCI 2 Control Register 1 */
volatile SCI2CR2STR _SCI2CR2;                              /* SCI 2 Control Register 2 */
volatile SCI2DRHSTR _SCI2DRH;                              /* SCI 2 Data Register High */
volatile SCI2DRLSTR _SCI2DRL;                              /* SCI 2 Data Register Low */
volatile SCI2SR1STR _SCI2SR1;                              /* SCI 2 Status Register 1 */
volatile SCI2SR2STR _SCI2SR2;                              /* SCI 2 Status Register 2 */
volatile SPIBRSTR _SPIBR;                                  /* SPI Baud Rate Register */
volatile SPICR1STR _SPICR1;                                /* SPI Control Register */
volatile SPICR2STR _SPICR2;                                /* SPI Control Register 2 */
volatile SPIDRSTR _SPIDR;                                  /* SPI Data Register */
volatile SPISRSTR _SPISR;                                  /* SPI Status Register */
volatile SYNRSTR _SYNR;                                    /* CRG Synthesizer Register */
volatile TIM0_CFORCSTR _TIM0_CFORC;                        /* TIM0 Timer Compare Force Register */
volatile TIM0_OC7DSTR _TIM0_OC7D;                          /* TIM0 Output Compare 7 Data Register */
volatile TIM0_OC7MSTR _TIM0_OC7M;                          /* TIM0 Output Compare 7 Mask Register */
volatile TIM0_PACTLSTR _TIM0_PACTL;                        /* TIM0 16-Bit Pulse Accumulator A Control Register */
volatile TIM0_PAFLGSTR _TIM0_PAFLG;                        /* TIM0 Pulse Accumulator A Flag Register */
volatile TIM0_TCTL1STR _TIM0_TCTL1;                        /* TIM0 Timer Control Registers 1 */
volatile TIM0_TCTL3STR _TIM0_TCTL3;                        /* TIM0 Timer Control Register 3 */
volatile TIM0_TFLG1STR _TIM0_TFLG1;                        /* TIM0 Main Timer Interrupt Flag 1 */
volatile TIM0_TFLG2STR _TIM0_TFLG2;                        /* TIM0 Main Timer Interrupt Flag 2 */
volatile TIM0_TIESTR _TIM0_TIE;                            /* TIM0 Timer Interrupt Enable Register */
volatile TIM0_TIOSSTR _TIM0_TIOS;                          /* TIM0 Timer Input Capture/Output Compare Select */
volatile TIM0_TSCR1STR _TIM0_TSCR1;                        /* TIM0 Timer System Control Register1 */
volatile TIM0_TSCR2STR _TIM0_TSCR2;                        /* TIM0 Timer System Control Register 2 */
volatile TIM0_TTOVSTR _TIM0_TTOV;                          /* TIM0 Timer Toggle On Overflow Register */
volatile TIM1_CFORCSTR _TIM1_CFORC;                        /* TIM1 Timer Compare Force Register */
volatile TIM1_OC7DSTR _TIM1_OC7D;                          /* TIM1 Output Compare 7 Data Register */
volatile TIM1_OC7MSTR _TIM1_OC7M;                          /* TIM1 Output Compare 7 Mask Register */
volatile TIM1_PACTLSTR _TIM1_PACTL;                        /* TIM1 16-Bit Pulse Accumulator A Control Register */
volatile TIM1_PAFLGSTR _TIM1_PAFLG;                        /* TIM1 Pulse Accumulator A Flag Register */
volatile TIM1_TCTL1STR _TIM1_TCTL1;                        /* TIM1 Timer Control Registers 1 */
volatile TIM1_TCTL3STR _TIM1_TCTL3;                        /* TIM1 Timer Control Register 3 */
volatile TIM1_TFLG1STR _TIM1_TFLG1;                        /* TIM1 Main Timer Interrupt Flag 1 */
volatile TIM1_TFLG2STR _TIM1_TFLG2;                        /* TIM1 Main Timer Interrupt Flag 2 */
volatile TIM1_TIESTR _TIM1_TIE;                            /* TIM1 Timer Interrupt Enable Register */
volatile TIM1_TIOSSTR _TIM1_TIOS;                          /* TIM1 Timer Input Capture/Output Compare Select */
volatile TIM1_TSCR1STR _TIM1_TSCR1;                        /* TIM1 Timer System Control Register1 */
volatile TIM1_TSCR2STR _TIM1_TSCR2;                        /* TIM1 Timer System Control Register 2 */
volatile TIM1_TTOVSTR _TIM1_TTOV;                          /* TIM1 Timer Toggle On Overflow Register */
volatile TIM2_CFORCSTR _TIM2_CFORC;                        /* TIM2 Timer Compare Force Register */
volatile TIM2_OC7DSTR _TIM2_OC7D;                          /* TIM2 Output Compare 7 Data Register */
volatile TIM2_OC7MSTR _TIM2_OC7M;                          /* TIM2 Output Compare 7 Mask Register */
volatile TIM2_PACTLSTR _TIM2_PACTL;                        /* TIM2 16-Bit Pulse Accumulator A Control Register */
volatile TIM2_PAFLGSTR _TIM2_PAFLG;                        /* TIM2 Pulse Accumulator A Flag Register */
volatile TIM2_TCTL1STR _TIM2_TCTL1;                        /* TIM2 Timer Control Registers 1 */
volatile TIM2_TCTL3STR _TIM2_TCTL3;                        /* TIM2 Timer Control Register 3 */
volatile TIM2_TFLG1STR _TIM2_TFLG1;                        /* TIM2 Main Timer Interrupt Flag 1 */
volatile TIM2_TFLG2STR _TIM2_TFLG2;                        /* TIM2 Main Timer Interrupt Flag 2 */
volatile TIM2_TIESTR _TIM2_TIE;                            /* TIM2 Timer Interrupt Enable Register */
volatile TIM2_TIOSSTR _TIM2_TIOS;                          /* TIM2 Timer Input Capture/Output Compare Select */
volatile TIM2_TSCR1STR _TIM2_TSCR1;                        /* TIM2 Timer System Control Register1 */
volatile TIM2_TSCR2STR _TIM2_TSCR2;                        /* TIM2 Timer System Control Register 2 */
volatile TIM2_TTOVSTR _TIM2_TTOV;                          /* TIM2 Timer Toggle On Overflow Register */
volatile VREGCTRL0STR _VREGCTRL0;                          /* VREG_3V3 - Control Register */
volatile WOMMSTR _WOMM;                                    /* Port M Wired-Or Mode Register */
volatile WOMSSTR _WOMS;                                    /* Port S Wired-Or Mode Register */
volatile ATDCTL23STR _ATDCTL23;                            /* ATD Control Register 23 */
volatile ATDCTL45STR _ATDCTL45;                            /* ATD Control Register 45 */
volatile ATDDIENSTR _ATDDIEN;                              /* ATD Input Enable Mask Register */
volatile ATDDR0STR _ATDDR0;                                /* ATD Conversion Result Register 0 */
volatile ATDDR1STR _ATDDR1;                                /* ATD Conversion Result Register 1 */
volatile ATDDR10STR _ATDDR10;                              /* ATD Conversion Result Register 10 */
volatile ATDDR11STR _ATDDR11;                              /* ATD Conversion Result Register 11 */
volatile ATDDR12STR _ATDDR12;                              /* ATD Conversion Result Register 12 */
volatile ATDDR13STR _ATDDR13;                              /* ATD Conversion Result Register 13 */
volatile ATDDR14STR _ATDDR14;                              /* ATD Conversion Result Register 14 */
volatile ATDDR15STR _ATDDR15;                              /* ATD Conversion Result Register 15 */
volatile ATDDR2STR _ATDDR2;                                /* ATD Conversion Result Register 2 */
volatile ATDDR3STR _ATDDR3;                                /* ATD Conversion Result Register 3 */
volatile ATDDR4STR _ATDDR4;                                /* ATD Conversion Result Register 4 */
volatile ATDDR5STR _ATDDR5;                                /* ATD Conversion Result Register 5 */
volatile ATDDR6STR _ATDDR6;                                /* ATD Conversion Result Register 6 */
volatile ATDDR7STR _ATDDR7;                                /* ATD Conversion Result Register 7 */
volatile ATDDR8STR _ATDDR8;                                /* ATD Conversion Result Register 8 */
volatile ATDDR9STR _ATDDR9;                                /* ATD Conversion Result Register 9 */
volatile DDRABSTR _DDRAB;                                  /* Port AB Data Direction Register */
volatile DDRADSTR _DDRAD;                                  /* Port AD Data Direction Register */
volatile PERADSTR _PERAD;                                  /* Port AD Pull Device Enable Register */
volatile PIEADSTR _PIEAD;                                  /* Port AD Interrupt Enable Register */
volatile PIFADSTR _PIFAD;                                  /* Port AD Interrupt Flag Register */
volatile PMFCNTASTR _PMFCNTA;                              /* PMF Counter A Register */
volatile PMFCNTBSTR _PMFCNTB;                              /* PMF Counter B Register */
volatile PMFCNTCSTR _PMFCNTC;                              /* PMF Counter C Register */
volatile PMFDTMASTR _PMFDTMA;                              /* PMF Deadtime A Register */
volatile PMFDTMBSTR _PMFDTMB;                              /* PMF Deadtime B Register */
volatile PMFDTMCSTR _PMFDTMC;                              /* PMF Deadtime C Register */
volatile PMFMODASTR _PMFMODA;                              /* PMF Counter Modulo A Register */
volatile PMFMODBSTR _PMFMODB;                              /* PMF Counter Modulo B Register */
volatile PMFMODCSTR _PMFMODC;                              /* PMF Counter Modulo C Register */
volatile PMFVAL0STR _PMFVAL0;                              /* PMF Value 0 Register */
volatile PMFVAL1STR _PMFVAL1;                              /* PMF Value 1 Register */
volatile PMFVAL2STR _PMFVAL2;                              /* PMF Value 2 Register */
volatile PMFVAL3STR _PMFVAL3;                              /* PMF Value 3 Register */
volatile PMFVAL4STR _PMFVAL4;                              /* PMF Value 4 Register */
volatile PMFVAL5STR _PMFVAL5;                              /* PMF Value 5 Register */
volatile PORTABSTR _PORTAB;                                /* Port AB Register */
volatile PPSADSTR _PPSAD;                                  /* Port AD Polarity Select Register */
volatile PTADSTR _PTAD;                                    /* Port AD I/O Register */
volatile PTIADSTR _PTIAD;                                  /* Port AD Input Register */
volatile PWMCNT01STR _PWMCNT01;                            /* PWM Channel Counter 01 Register */
volatile PWMCNT23STR _PWMCNT23;                            /* PWM Channel Counter 23 Register */
volatile PWMCNT45STR _PWMCNT45;                            /* PWM Channel Counter 45 Register */
volatile PWMDTY01STR _PWMDTY01;                            /* PWM Channel Duty 01 Register */
volatile PWMDTY23STR _PWMDTY23;                            /* PWM Channel Duty 23 Register */
volatile PWMDTY45STR _PWMDTY45;                            /* PWM Channel Duty 45 Register */
volatile PWMPER01STR _PWMPER01;                            /* PWM Channel Period 01 Register */
volatile PWMPER23STR _PWMPER23;                            /* PWM Channel Period 23 Register */
volatile PWMPER45STR _PWMPER45;                            /* PWM Channel Period 45 Register */
volatile RDRADSTR _RDRAD;                                  /* Port AD Reduced Drive Register */
volatile SCI0BDSTR _SCI0BD;                                /* SCI 0 Baud Rate Register */
volatile SCI1BDSTR _SCI1BD;                                /* SCI 1 Baud Rate Register */
volatile SCI2BDSTR _SCI2BD;                                /* SCI 2 Baud Rate Register */
volatile TIM0_PACNTSTR _TIM0_PACNT;                        /* TIM0 Pulse Accumulators Count Register */
volatile TIM0_TC4STR _TIM0_TC4;                            /* TIM0 Timer Input Capture/Output Compare Register 4 */
volatile TIM0_TC5STR _TIM0_TC5;                            /* TIM0 Timer Input Capture/Output Compare Register 5 */
volatile TIM0_TC6STR _TIM0_TC6;                            /* TIM0 Timer Input Capture/Output Compare Register 6 */
volatile TIM0_TC7STR _TIM0_TC7;                            /* TIM0 Timer Input Capture/Output Compare Register 7 */
volatile TIM0_TCNTSTR _TIM0_TCNT;                          /* TIM0 Timer Count Register */
volatile TIM1_PACNTSTR _TIM1_PACNT;                        /* TIM1 Pulse Accumulators Count Register */
volatile TIM1_TC4STR _TIM1_TC4;                            /* TIM1 Timer Input Capture/Output Compare Register 4 */
volatile TIM1_TC5STR _TIM1_TC5;                            /* TIM1 Timer Input Capture/Output Compare Register 5 */
volatile TIM1_TC6STR _TIM1_TC6;                            /* TIM1 Timer Input Capture/Output Compare Register 6 */
volatile TIM1_TC7STR _TIM1_TC7;                            /* TIM1 Timer Input Capture/Output Compare Register 7 */
volatile TIM1_TCNTSTR _TIM1_TCNT;                          /* TIM1 Timer Count Register */
volatile TIM2_PACNTSTR _TIM2_PACNT;                        /* TIM2 Pulse Accumulators Count Register */
volatile TIM2_TC4STR _TIM2_TC4;                            /* TIM2 Timer Input Capture/Output Compare Register 4 */
volatile TIM2_TC5STR _TIM2_TC5;                            /* TIM2 Timer Input Capture/Output Compare Register 5 */
volatile TIM2_TC6STR _TIM2_TC6;                            /* TIM2 Timer Input Capture/Output Compare Register 6 */
volatile TIM2_TC7STR _TIM2_TC7;                            /* TIM2 Timer Input Capture/Output Compare Register 7 */
volatile TIM2_TCNTSTR _TIM2_TCNT;                          /* TIM2 Timer Count Register */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.33 for 
**     the Motorola HCS12 series of microcontrollers.
**
** ###################################################################
*/
